#!/usr/bin/env node
/**
 * serve.js — LAN-ready HTTPS dev server for VDO.Ninja
 *
 * Requires:
 *   - ssl/cert.pem  \  generated by setup-certs.sh (or setup-certs.bat)
 *   - ssl/key.pem   /
 *
 * Usage:
 *   node serve.js [port]     (default: 8443)
 *
 * Then open on THIS machine:   https://localhost:8443
 * Open on LAN devices:         https://<your-LAN-ip>:8443
 *
 * On first visit browsers will show a certificate warning — click
 * "Advanced → Proceed" (Chrome) or "Accept the Risk" (Firefox).
 * This is normal for self-signed certs.
 */

const https  = require('https');
const http   = require('http');   // only used to detect LAN IP
const fs     = require('fs');
const path   = require('path');
const url    = require('url');
const os     = require('os');

const PORT = parseInt(process.argv[2]) || 8443;

// ── TLS cert ─────────────────────────────────────────────────────────────────
const CERT_DIR  = path.join(__dirname, 'ssl');
const CERT_FILE = path.join(CERT_DIR, 'cert.pem');
const KEY_FILE  = path.join(CERT_DIR, 'key.pem');

if (!fs.existsSync(CERT_FILE) || !fs.existsSync(KEY_FILE)) {
  console.error('');
  console.error('  ❌  SSL certificate not found!');
  console.error('  Run one of these first:');
  console.error('      bash setup-certs.sh        (Mac / Linux)');
  console.error('      setup-certs.bat            (Windows)');
  console.error('');
  process.exit(1);
}

const TLS_OPTIONS = {
  key:  fs.readFileSync(KEY_FILE),
  cert: fs.readFileSync(CERT_FILE),
};

// ── MIME types ────────────────────────────────────────────────────────────────
const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.js':   'application/javascript; charset=utf-8',
  '.css':  'text/css; charset=utf-8',
  '.json': 'application/json',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif':  'image/gif',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.woff': 'font/woff',
  '.woff2':'font/woff2',
  '.ttf':  'font/ttf',
  '.eot':  'application/vnd.ms-fontobject',
  '.mp4':  'video/mp4',
  '.webm': 'video/webm',
  '.ogg':  'audio/ogg',
  '.mp3':  'audio/mpeg',
  '.xml':  'application/xml',
  '.txt':  'text/plain',
  '.md':   'text/plain',
  '.map':  'application/json',
};

// Cross-Origin-Isolation headers — required for SharedArrayBuffer
// Using 'credentialless' for COEP instead of 'require-corp' so that
// credentialless iframes (Chrome 96+) can load cross-origin content
// (like vdo.ninja) without the remote server needing explicit CORP headers.
// Firefox does not support credentialless iframes, so on Firefox any COEP
// will block cross-origin iframes — but at least this won't break Chrome/Edge.
const COOP_COEP = {
  'Cross-Origin-Opener-Policy':   'same-origin',
  'Cross-Origin-Embedder-Policy': 'credentialless',
};

// ── File root ─────────────────────────────────────────────────────────────────
const ROOTS = [
  path.join(__dirname, 'vdoninja'),
  __dirname,
];

function findRoot() {
  for (const r of ROOTS) {
    if (fs.existsSync(path.join(r, 'index.html'))) return r;
  }
  return __dirname;
}

const ROOT = findRoot();

// ── Request handler ───────────────────────────────────────────────────────────
function handler(req, res) {
  let pathname = url.parse(req.url).pathname;
  try { pathname = decodeURIComponent(pathname); } catch (e) {}

  const safePath = path.normalize(pathname).replace(/^(\.\.)[\/\\]/g, '');

  const candidates = [
    path.join(ROOT, safePath),
    path.join(ROOT, safePath + '.html'),
    path.join(ROOT, safePath, 'index.html'),
    path.join(ROOT, 'index.html'),
  ];

  let filePath = null;
  for (const c of candidates) {
    try {
      if (fs.existsSync(c) && fs.statSync(c).isFile()) { filePath = c; break; }
    } catch (_) {}
  }

  if (!filePath) {
    res.writeHead(404, { 'Content-Type': 'text/plain', ...COOP_COEP });
    res.end('404 Not Found: ' + pathname);
    return;
  }

  const ext  = path.extname(filePath).toLowerCase();
  const mime = MIME[ext] || 'application/octet-stream';

  fs.readFile(filePath, (err, data) => {
    if (err) {
      res.writeHead(500, { 'Content-Type': 'text/plain', ...COOP_COEP });
      res.end('500 Internal Error');
      return;
    }
    res.writeHead(200, {
      'Content-Type':   mime,
      'Content-Length': data.length,
      'Cache-Control':  'no-cache',
      ...COOP_COEP,
    });
    res.end(data);
  });
}

// ── Detect LAN IP ─────────────────────────────────────────────────────────────
function getLanIP() {
  const ifaces = os.networkInterfaces();
  for (const name of Object.keys(ifaces)) {
    for (const iface of ifaces[name]) {
      if (iface.family === 'IPv4' && !iface.internal) return iface.address;
    }
  }
  return null;
}

// ── Start server on ALL interfaces (0.0.0.0) so LAN devices can reach it ─────
const server = https.createServer(TLS_OPTIONS, handler);

server.listen(PORT, '0.0.0.0', () => {
  const lan = getLanIP();
  console.log('');
  console.log('  ✅  VDO.Ninja HTTPS server running');
  console.log(`  Serving from: ${ROOT}`);
  console.log('');
  console.log(`  This machine:   https://localhost:${PORT}`);
  console.log(`  This machine:   https://localhost:${PORT}/iframe.html`);
  if (lan) {
    console.log('');
    console.log(`  LAN devices:    https://${lan}:${PORT}`);
    console.log(`  LAN devices:    https://${lan}:${PORT}/iframe.html`);
    console.log('');
    console.log('  ⚠️   LAN devices will see a cert warning — click Advanced → Proceed');
  }
  console.log('');
  console.log('  Press Ctrl+C to stop.');
  console.log('');
});
